#!/bin/bash
set -e

cat /etc/default/grub
sleep 5
cat /etc/mkinitcpio.conf
exit

sed -i -e 's/#BUILDDIR/BUILDDIR/' /etc/makepkg.conf

# Build Dir
echo "%nobody ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/nobody
chsh -s /bin/bash nobody
mkdir -p /Build
chgrp nobody /Build
chmod g+ws /Build
setfacl -m u::rwx,g::rwx /Build
setfacl -d --set u::rwx,g::rwx,o::- /Build

# AUR packages
#cd /Build
#sudo -u nobody git clone https://aur.archlinux.org/yay-bin.git
#cd yay-bin
#sudo -u nobody makepkg
#pacman -U *.pkg.tar.zst --noconfirm
#cd ..

cd /Build
while read i; do
    sudo -u nobody git clone https://aur.archlinux.org/$i.git
    cd $i
    [[ $i == yay-bin ]] || deps=$(yay -Si $i | awk '/^Depends On/,/^Check Deps/' | grep -v "None" | sed -e 's/^.*: //' | tr '\r\n' ' ' | tr -s ' ')
    [[ -n $deps ]] && pacman -S $deps --asdeps --noconfirm
    sudo -u nobody makepkg
    pacman -U *.pkg.tar.zst --noconfirm
    cd ..
done <<< "yay-bin
c-lolcat
grub-git
powerline-console-fonts-git"

sed -i '/HOOKS=/d' /etc/mkinitcpio.conf
echo 'HOOKS="base udev autodetect keyboard keymap consolefont modconf block encrypt lvm2 filesystems fsck darch"/' >> /etc/mkinitcpio.conf
mkinitcpio -p linux

sed -i -E '/GRUB_ENABLE_CRYPTODISK=/d;s/(GRUB_CMDLINE_LINUX=".*)"/\1 cryptdevice=PARTLABEL=lvmcrypt:lvmcrypt' /etc/default/grub

tar xzvf /etc/darch/darch.tar.gz
grub-mkconfig -o /boot/grub/grub.cfg
